[package]
name = "ibus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
dbus = "0.9"
glib = "0.14"
thiserror = "1"
